name: update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v7

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update flake.lock
        run: nix flake update --commit-lock-file

      - name: Update pipeasio
        run: nix run 'nixpkgs#nix-update' -- --flake --commit 'pipeasio'

      - name: Update rs-asio
        run: nix run 'nixpkgs#nix-update' -- --flake --commit 'rs-asio'      

      - name: Push changes
        run: git push origin master
